project:
  type: website

website:
  title: "rampoines"
  site-url: https://rampoines.cat
  description: "Jardí digital ple de rampoines"

  navbar:
    left:
      - href: novetats/index.qmd
        text: butlletí

      - href: posts/00_index_notes.qmd
        text: notes

      - href: projectes.qmd
        text: projectes

      - href: sobre_aixo.qmd
        text: sobre això

format:
  html:
    theme: minty
    anchor-sections: false
    math: false
    css: styles.css

lang: ca

execute: 
  engine: knitr
  python: false