project:
  type: website

website:
  title: "rampoines"
  site-url: https://reigborda.github.io/rampoines

  navbar:
    left:
      - href: novetats/index_novetats.qmd
        text: novetats

      - href: posts/00_index_notes.qmd
        text: notes

      - href: projectes.qmd
        text: projectes

      - href: sobre_aixo.qmd
        text: sobre això

format:
  html:
    theme: minty
    anchor-sections: false
    math: false
    css: styles.css

lang: ca

execute: 
  engine: knitr
  python: false