project:
  type: website

website:
  title: "rampoines"

  navbar:
    left:
      - href: butlleti.qmd
        text: Butlletí

      - href: posts/index_blog.qmd
        text: Blog

      - href: projectes.qmd
        text: Projectes

      - href: apunts.qmd
        text: Apunts

format:
  html:
    theme: minty
    anchor-sections: false
    math: false
    css: styles.css

language:
  en:
    search:
      placeholder: "Cerca"
    listing:
      filter: "Filtrar"
      all: "Tot"

execute: 
  engine: knitr
  python: false