---
title: "biografies terapitzades"
date: 2026-07-09
description: "ni tothom ha d'anar a teràpia, ni la salut és constitutiva d'identitats"
categories:
  - pensament
  - psicologia
comments:
  giscus:
    repo: reigborda/rampoines
    repo-id: R_kgDOTJ7a8w
    category: General
    category-id: DIC_kwDOTJ7a884DAUNP
    mapping: pathname
    reactions-enabled: true
    input-position: bottom
    theme: light
    loading: lazy
---

Aquesta entrada conté les següents parts:

1.  El relat autobiogràfic
2.  La terapització i l'autoconsciència
3.  Narcisisme victimista
4.  Salut identitària

------------------------------------------------------------------------

::: {.alert .alert-dismissible .alert-danger}
<button type="button" class="btn-close" data-bs-dismiss="alert">

</button>

**Advertència** Quan parlo de psicologia és de manera científica. Les pseudociències ni les discuteixo, són estafes i posen en perill la salut i la vida de les persones.
:::

### 1. El relat autobiogràfic

Quan comences un procés terapèutic, generalment en la fase inicial de la intervenció, crees un relat autobiogràfic per contextualitzar el malestar o la problemàtica actual en la "línia de vida" \[*concepte utilitzat en psicologia*\]. La hipòtesi amb la que treballaré avui és que aquest relat és problemàtic, sobretot si no es pren com a eina puntual sinó com a explicació vital real.

La vivència humana és tan complexa com rica, no té una *línia*. És cert que la nostra concepció del temps és lineal, però passen tantes coses alhora en les nostres vides, que des del moment en què defineixes un eix narratiu sobre el passat, estàs manipulant aquesta vivència establint un ordre de prioritats. Passen tantes coses que unes les has de descartar sobre altres que ressaltes. I quin és el model del relat psicològic de la línia de vida? Es presenta com a precursor del problema un fil de dolor des del que explicar la pròpia història, incidint en les experiències negatives, confrontatives, violentes i contradictòries.

I no nego que poder buscar les causes biogràfiques d'un problema de salut mental pugui ser eficient i eficaç. El problema rau en que el pacient es cregui que això és una explicació de la seva vida i que, per tant, condicioni la seva manera d'actuar i pensar en l'actualitat i en el futur.

### 2. La terapització i l'autoconsciència

### 3. Narcisisme victimista

::: definition-box
*"- Te la mires amb orgull, la teva ferida? Et fa sentir tràgic i important?*

*- No ho sé.*

*- Pensa-hi. Potser estàs actuant en un teatre grandiós en què l'únic espectador ets tu."*

 

A l'est de l'Edèn - John Steinbeck
:::

### 4. Salut identitària

En què et fixes quan relates la teva vida? La terapització constant i l'autoconsciència solen presentar un fil de dolor des del que explicar la teva història, incidint en la part negativa, confrontativa i contradictòria. Em nego a relatar-me des d'un discurs del dolor, de la lluita i la superació. "Guau! Ets una supervivent!" Com tots, no? si no sobrevivim, morim. D'això tracta la vida.
