name: Publish Quarto site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.rstudio.com/all/__linux__/jammy/latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore R packages (renv)
        run: Rscript -e "renv::restore(prompt = FALSE, repos = 'https://cloud.r-project.org')"

      - name: Render Quarto site
        run: quarto render .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4